
["Server config"]
	#The speed multiplier when sprinting
	"Speed Multiplier" = 1.0E-4
	#Ak74u dmg
	"Ak74u Dmg" = 6.0
	#ASVal dmg
	"AsVal Dmg" = 3.0
	#Colt1911 dmg
	"Colt1911 Dmg" = 4.0
	#Galil dmg
	"Galil Dmg" = 9.0
	#Kar98k dmg
	"Kar98k Dmg" = 10.0
	#LugerP08 dmg
	"LugerP08 Dmg" = 3.0
	#Model37 Dmg dmg
	"Model37 Dmg" = 1.5
	#Mp40 dmg
	"Mp40 Dmg" = 5.0
	#Mp5 dmg
	"Mp5 Dmg" = 6.0
	#Pirate Pistol Damage dmg
	"Pirate Pistol Dmg" = 4.0
	#Pirate Rifle dmg
	"Pirate Rifle Dmg" = 6.0
	#Revolver dmg
	"Revolver Dmg" = 7.0
	#Sten dmg
	"Sten Dmg" = 4.3
	#Thompson dmg
	"Thompson Dmg" = 2.0
	#Bizon dmg
	"Bizon Dmg" = 3.0
	#Skorpion dmg
	"Skorpion Dmg" = 4.0
	#Winchester dmg
	"Winchester Dmg" = [3.0, 8.0]

