modules_right = []

[general]
	disable_mod = false
	hide_bossbar = true
	shadow_text = true
	auto_start = false
	animationSpeed = 1.0
	hide_debug_crosshair = false
	background_color = 1867534416
	space_modules = false
	always_show_profiler = true
	animations = false
	fontScale = 1.0
	hide_sidebar = true
	always_show_tps = true

[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	enabled = true
	color_low = 16733525

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	enabled = true

	[modules_left.lines]
		chunk_coords = true
		player_coords = true
		block_coords = true
		chunk_relative_coords = true

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	enabled = true

	[modules_left.lines]
		entities = true
		water_creature = true
		underground_water_creature = true
		ambient = true
		particles = true
		axolotls = true
		creature = true
		water_ambient = true
		monster = true
		misc = true

[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		misc_left = true

