storagenetwork = false
tconstruct = true
sophisticatedbackpacks = true
fastfurnace = true
ironfurnaces = false
occultism = false
jei = true
ae2 = false
extendedcrafting = false
refinedstorageaddons = false
craftingcraft = false
toms_storage = true
sophisticatedcore = true
refinedstorage = false
prettypipes = false
fastsuite = true
fastbench = true
cyclic = false

